# cm-13.0-ZNH0E.yaml
#
# Crowdin configuration file for CyanogenMod
#
# Copyright (C) 2014-2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api_key_env: CM_CROWDIN_API_KEY
base_path_env: CM_CROWDIN_STABLE_BASE_PATH
base_path_contains_branch_subfolders: true
project_identifier: cyanogenmod
preserve_hierarchy: true

files:
# Frameworks

  # framework-res
  -
    source:      '/frameworks/base/core/res/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: &anchor
      android_code:
        af: af
        am: am
        ar: ar
        ast: ast-rES
        az: az-rAZ
        be: be
        bg: bg
        bn: bn-rBD
        ca: ca
        cs: cs
        cy: cy
        da: da
        de: de
        el: el
        en-AU: en-rAU
        en-GB: en-rGB
        en-IN: en-rIN
        en-PT: en-rPT
        eo: eo
        es-ES: es
        es-MX: es-rMX
        es-US: es-rUS
        et: et-rEE
        eu: eu-rES
        fa: fa
        fi: fi
        fr: fr
        fr-CA: fr-rCA
        fy-NL: fy-rNL
        gl: gl-rES
        gu-IN: gu-rIN
        he: iw
        hi: hi
        hr: hr
        hu: hu
        hy-AM: hy-rAM
        id: in
        is: is-rIS
        it: it
        ja: ja
        ka: ka-rGE
        kk: kk-rKZ
        km: km-rKH
        kn: kn-rIN
        ko: ko
        ku: ku
        ky: ky-rKG
        lb: lb
        lo: lo-rLA
        lt: lt
        lv: lv
        mk: mk-rMK
        ml-IN: ml-rIN
        mn: mn-rMN
        mr: mr-rIN
        ms: ms-rMY
        my: my-rMM
        nb: nb
        ne-NP: ne-rNP
        nl: nl
        pa-IN: pa-rIN
        pl: pl
        pt-PT: pt-rPT
        pt-BR: pt-rBR
        rm-CH: rm
        ro: ro
        ru: ru
        si-LK: si-rLK
        sk: sk
        sl: sl
        sq: sq-rAL
        sr: sr
        sv-SE: sv
        sw: sw
        ta: ta-rIN
        te: te-rIN
        th: th
        tl: tl
        tr: tr
        ug: ug
        uk: uk
        ur-PK: ur-rPK
        uz: uz-rUZ
        vi: vi
        zh-CN: zh-rCN
        zh-HK: zh-rHK
        zh-TW: zh-rTW
        zu: zu

  # Keyguard
  -
    source:      '/frameworks/base/packages/Keyguard/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # SettingsLib
  -
    source:      '/frameworks/base/packages/SettingsLib/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # SystemUI
  -
    source:      '/frameworks/base/packages/SystemUI/res/values/cm_arrays.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/frameworks/base/packages/SystemUI/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# Packages

  # AudioFX
  -
    source:      '/packages/apps/AudioFX/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Bluetooth
  -
    source:      '/packages/apps/Bluetooth/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # BluetoothExt
  -
    source:      '/packages/apps/BluetoothExt/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/BluetoothExt/res/values/strings_dun.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/BluetoothExt/res/values/strings_ftp.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/BluetoothExt/res/values/strings_map.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/BluetoothExt/res/values/strings_sap.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Browser
  -
    source:      '/packages/apps/Browser/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Calculator
  -
    source:      '/packages/apps/Calculator/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Calendar
  -
    source:      '/packages/apps/Calendar/res/values/cm_plurals.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Calendar/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Camera2
  -
    source:      '/packages/apps/Camera2/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # CMBugReport
  -
    source:      '/packages/apps/CMBugReport/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # CMFileManager
  -
    source:      '/packages/apps/CMFileManager/res/values/plurals.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/CMFileManager/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # CMUpdater
  -
    source:      '/packages/apps/CMUpdater/res/values/plurals.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/CMUpdater/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # CMWallpapers
  -
    source:      '/packages/apps/CMWallpapers/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Contacts
  -
    source:      '/packages/apps/Contacts/res/values/cm_plurals.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Contacts/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # ContactsCommon
  -
    source:      '/packages/apps/ContactsCommon/res/values/cm_plurals.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/ContactsCommon/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # DeskClock
  -
    source:      '/packages/apps/DeskClock/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Dialer
  -
    source:      '/packages/apps/Dialer/res/values/cm_arrays.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Dialer/res/values/cm_plurals.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Dialer/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Eleven
  -
    source:      '/packages/apps/Eleven/res/values/plurals.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Eleven/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Email
  -
    source:      '/packages/apps/Email/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Gallery2
  -
    source:      '/packages/apps/Gallery2/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Gallery2/res/values/codeaurora_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # InCallUI
  -
    source:      '/packages/apps/InCallUI/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/InCallUI/res/values/qtistrings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # LockClock
  -
    source:      '/packages/apps/LockClock/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Messaging
  -
    source:      '/packages/apps/Messaging/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # PhoneCommon
  -
    source:      '/packages/apps/PhoneCommon/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Profiles
  -
    source:      '/packages/apps/Profiles/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Screencast
  -
    source:      '/packages/apps/Screencast/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Settings
  -
    source:      '/packages/apps/Settings/res/values/cm_plurals.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Settings/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # SetupWizard
  -
    source:      '/packages/apps/SetupWizard/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Snap
  -
    source:      '/packages/apps/Snap/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Snap/res/values/qcomstrings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Snap/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # SoundRecorder
  -
    source:      '/packages/apps/SoundRecorder/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Stk
  -
    source:      '/packages/apps/Stk/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Terminal
  -
    source:      '/packages/apps/Terminal/res/values/arrays.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Terminal/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # ThemeChooser
  -
    source:      '/packages/apps/ThemeChooser/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Trebuchet
  -
    source:      '/packages/apps/Trebuchet/res/values/cm_arrays.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/apps/Trebuchet/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # TvSettings
  -
    source:      '/packages/apps/TvSettings/Settings/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # UnifiedEmail
  -
    source:      '/packages/apps/UnifiedEmail/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# Input methods

  # LatinIME
  -
    source:      '/packages/inputmethods/LatinIME/java/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# Providers

  # DownloadProvider
  -
    source:      '/packages/providers/DownloadProvider/res/values/cm_plurals.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/providers/DownloadProvider/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # ThemesProvider
  -
    source:      '/packages/providers/ThemesProvider/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# Screensavers

  # PhotoTable
  -
    source:      '/packages/screensavers/PhotoTable/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# Services

  # Mms
  -
    source:      '/packages/services/Mms/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Telecomm
  -
    source:      '/packages/services/Telecomm/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # Telephony
  -
    source:      '/packages/services/Telephony/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/services/Telephony/res/values/qtistrings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# Wallpapers

  # Galaxy4
  -
    source:      '/packages/wallpapers/Galaxy4/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # PhaseBeam
  -
    source:      '/packages/wallpapers/PhaseBeam/res/values/cm_strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # PhotoPhase
  -
    source:      '/packages/wallpapers/PhotoPhase/res/values/plurals.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/packages/wallpapers/PhotoPhase/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# Vendor

  # CM SDK
  -
    source:      '/vendor/cmsdk/cm/res/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # CMSettingsProvider
  -
    source:      '/vendor/cmsdk/packages/CMSettingsProvider/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

# Device specific

  # fmapp2
  -
    source:      '/hardware/qcom/fm/fmapp2/res/values/arrays.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
  -
    source:      '/hardware/qcom/fm/fmapp2/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor

  # FMRecord
  -
    source:      '/hardware/qcom/fm/FMRecord/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: *anchor
