# lineage-17.1.yaml
#
# Crowdin configuration file for LineageOS
#
# Copyright (C) 2014-2016 The CyanogenMod Project
# Copyright (C) 2017-2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api_key_env: LINEAGE_CROWDIN_API_KEY
base_path_env: LINEAGE_CROWDIN_BASE_PATH_LINEAGE_17_1
project_identifier: lineageos
preserve_hierarchy: true

files:
# Frameworks

  # framework-res
  -
    source:      '/device/oneplus/sm8150-common/camera_helper/res/values/strings.xml'
    translation: '/%original_path%-%android_code%/%original_file_name%'
    languages_mapping: &anchor
      android_code:
        # Afrikaans
        af: af
        # Albanian
        sq: sq
        # Amharic
        am: am
        # Arabic
        ar: ar
        # Armenian
        hy-AM: hy
        # Arpitan - LineageOS
        frp: frp
        # Assamese
        as: as
        # Asturian - LineageOS
        ast: ast-rES
        # Azerbaijani
        az: az
        # Basque
        eu: eu
        # Belarusian
        be: be
        # Bengali
        bn: bn
        # Bosnian
        bs: bs
        # Breton - LineageOS
        br-FR: br-rFR
        # Bulgarian
        bg: bg
        # Burmese
        my: my
        # Catalan
        ca: ca
        # Chinese Simplified
        zh-CN: zh-rCN
        # Chinese Traditional
        zh-TW: zh-rTW
        # Chinese Traditional, Hong Kong
        zh-HK: zh-rHK
        # Croatian
        hr: hr
        # Czech
        cs: cs
        # Danish
        da: da
        # Dutch
        nl: nl
        # English, Australia
        en-AU: en-rAU
        # English, Canada
        en-CA: en-rCA
        # English, India
        en-IN: en-rIN
        # English, United Kingdom
        en-GB: en-rGB
        # Esperanto - LineageOS
        eo: eo
        # Estonian
        et: et
        # Filipino - LineageOS
        fil: fil
        # Finnish
        fi: fi
        # French
        fr: fr
        # French, Canada
        fr-CA: fr-rCA
        # Frisian - LineageOS
        fy-NL: fy-rNL
        # Galician
        gl: gl
        # Georgian
        ka: ka
        # German
        de: de
        # Greek
        el: el
        # Gujarati
        gu-IN: gu
        # Hebrew
        he: iw
        # Hindi
        hi: hi
        # Hungarian
        hu: hu
        # Icelandic
        is: is
        # Indonesian
        id: in
        # Irish - LineageOS
        ga-IE: ga-rIE
        # Italian
        it: it
        # Japanese
        ja: ja
        # Kabyle - LineageOS
        kab: kab-rDZ
        # Kannada
        kn: kn
        # Kashubian - LineageOS
        csb: csb
        # Kazakh
        kk: kk
        # Khmer
        km: km
        # Korean
        ko: ko
        # Kurdish - LineageOS
        ku: ku
        # Kyrgyz
        ky: ky
        # Lao
        lo: lo
        # Latvian
        lv: lv
        # Lithuanian
        lt: lt
        # Luxembourgish - LineageOS
        lb: lb
        # Macedonian (FYROM)
        mk: mk
        # Malay
        ms: ms
        # Malayalam
        ml-IN: ml
        # Marathi
        mr: mr
        # Mongolian
        mn: mn
        # Nepali
        ne-NP: ne
        # Norwegian Bokmal
        nb: nb
        # Occitan - LineageOS
        oc: oc
        # Oriya
        or: or
        # Persian
        fa: fa
        # Pirate English - LineageOS
        en-PT: en-rPT
        # Polish
        pl: pl
        # Portuguese
        pt-PT: pt-rPT
        # Portuguese, Brazilian
        pt-BR: pt-rBR
        # Punjabi
        pa-IN: pa
        # Romanian
        ro: ro
        # Romansh - LineageOS
        rm-CH: rm
        # Russian
        ru: ru
        # Sardinian - LineageOS
        sc: sc-rIT
        # Scottish Gaelic - LineageOS
        gd: gd
        # Serbian (Cyrillic)
        sr: sr
        # Serbian (Latin)
        sr-CS: b+sr+Latn
        # Sinhala
        si-LK: si
        # Slovak
        sk: sk
        # Slovenian
        sl: sl
        # Spanish
        es-ES: es
        # Spanish, Colombia - LineageOS
        es-CO: es-rCO
        # Spanish, Mexico - LineageOS
        es-MX: es-rMX
        # Spanish, United States
        es-US: es-rUS
        # Sundanese - LineageOS
        su: su
        # Swahili
        sw: sw
        # Swedish
        sv-SE: sv
        # Tagalog
        tl: tl
        # Tamil
        ta: ta
        # Telugu
        te: te
        # Thai
        th: th
        # Turkish
        tr: tr
        # Ukrainian
        uk: uk
        # Urdu (Pakistan)
        ur-PK: ur
        # Uyghur - LineageOS
        ug: ug
        # Uzbek
        uz: uz
        # Venetian - LineageOS
        vec: vec
        # Vietnamese
        vi: vi
        # Welsh - LineageOS
        cy: cy
        # Zulu
        zu: zu
